package Test;

/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Pivotal tc Runtime 3.0.2.SR2/8.0.15.B.RELEASE
 * Generated at: 2019-06-08 13:56:05 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */


import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class Jsp extends org.apache.jasper.runtime.HttpJspBase
        implements org.apache.jasper.runtime.JspSourceDependent {


    private static final javax.servlet.jsp.JspFactory _jspxFactory =
            javax.servlet.jsp.JspFactory.getDefaultFactory();

    private static java.util.Map<java.lang.String, java.lang.Long> _jspx_dependants;

    static {
        _jspx_dependants = new java.util.HashMap<java.lang.String, java.lang.Long>(5);
        _jspx_dependants.put("jar:file:/F:/tool/sts-bundle/pivotal-tc-server-developer-3.0.2.SR2/base-instance/wtpwebapps/Shopping/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153356282000L));
        _jspx_dependants.put("/WEB-INF/lib/shiro-web-1.2.4.jar", Long.valueOf(1559700661846L));
        _jspx_dependants.put("/../WEB-INF/views/commons/nav.jsp", Long.valueOf(1560002157354L));
        _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1543762135273L));
        _jspx_dependants.put("jar:file:/F:/tool/sts-bundle/pivotal-tc-server-developer-3.0.2.SR2/base-instance/wtpwebapps/Shopping/WEB-INF/lib/shiro-web-1.2.4.jar!/META-INF/shiro.tld", Long.valueOf(1436273924000L));
    }

    private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fshiro_005fnotAuthenticated;
    private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fshiro_005fauthenticated;
    private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fshiro_005fhasAnyRoles_0026_005fname;
    private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fshiro_005fhasRole_0026_005fname;
    private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;

    private javax.el.ExpressionFactory _el_expressionfactory;
    private org.apache.tomcat.InstanceManager _jsp_instancemanager;

    public java.util.Map<java.lang.String, java.lang.Long> getDependants() {
        return _jspx_dependants;
    }

    public void _jspInit() {
        _005fjspx_005ftagPool_005fshiro_005fnotAuthenticated = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
        _005fjspx_005ftagPool_005fshiro_005fauthenticated = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
        _005fjspx_005ftagPool_005fshiro_005fhasAnyRoles_0026_005fname = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
        _005fjspx_005ftagPool_005fshiro_005fhasRole_0026_005fname = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
        _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
        _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
    }

    public void _jspDestroy() {
        _005fjspx_005ftagPool_005fshiro_005fnotAuthenticated.release();
        _005fjspx_005ftagPool_005fshiro_005fauthenticated.release();
        _005fjspx_005ftagPool_005fshiro_005fhasAnyRoles_0026_005fname.release();
        _005fjspx_005ftagPool_005fshiro_005fhasRole_0026_005fname.release();
        _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
    }

    public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
            throws java.io.IOException, javax.servlet.ServletException {

        final java.lang.String _jspx_method = request.getMethod();
        if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
            response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
            return;
        }

        final javax.servlet.jsp.PageContext pageContext;
        javax.servlet.http.HttpSession session = null;
        final javax.servlet.ServletContext application;
        final javax.servlet.ServletConfig config;
        javax.servlet.jsp.JspWriter out = null;
        final java.lang.Object page = this;
        javax.servlet.jsp.JspWriter _jspx_out = null;
        javax.servlet.jsp.PageContext _jspx_page_context = null;


        try {
            response.setContentType("text/html;charset=UTF-8");
            pageContext = _jspxFactory.getPageContext(this, request, response,
                    null, true, 8192, true);
            _jspx_page_context = pageContext;
            application = pageContext.getServletContext();
            config = pageContext.getServletConfig();
            session = pageContext.getSession();
            out = pageContext.getOut();
            _jspx_out = out;

            out.write("\n");
            out.write("\n");
            out.write("\n");
            out.write("\n");
            out.write(" ");
            out.write('\n');
            out.write('\n');
            out.write('\n');
            out.write('\n');
            org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../commons/head.jsp", out, false);
            out.write("\n");
            out.write("<div class=\"wrapper\">\n");
            out.write("    <header class=\"main-header\">\n");
            out.write("        <!-- Logo -->\n");
            out.write("        <a href=\"\" class=\"logo\">\n");
            out.write("            <!-- mini logo for sidebar mini 50x50 pixels -->\n");
            out.write("            <span class=\"logo-mini\">\n");
            out.write("     <img alt=\"\" src=\"");
            out.print(request.getContextPath());
            out.write("/img/2.jpg\" width=\"40px\" height=\"40px\">\n");
            out.write("  </span>\n");
            out.write("            <span class=\"logo-lg\">移动电子商务系统</span>\n");
            out.write("        </a>\n");
            out.write("        <!-- Header Navbar -->\n");
            out.write("        <nav class=\"navbar navbar-static-top\" role=\"navigation\">\n");
            out.write("            <!-- Sidebar toggle button-->\n");
            out.write("            <a href=\"#\" class=\"sidebar-toggle\" data-toggle=\"offcanvas\" role=\"button\">\n");
            out.write("                <span class=\"sr-only\">Toggle navigation</span>\n");
            out.write("            </a>\n");
            out.write("            <!-- Navbar Right Menu -->\n");
            out.write("            <div class=\"navbar-custom-menu\">\n");
            out.write("                <ul class=\"nav navbar-nav\">\n");
            out.write("                    ");
            //  shiro:notAuthenticated
            org.apache.shiro.web.tags.NotAuthenticatedTag _jspx_th_shiro_005fnotAuthenticated_005f0 = (org.apache.shiro.web.tags.NotAuthenticatedTag) _005fjspx_005ftagPool_005fshiro_005fnotAuthenticated.get(org.apache.shiro.web.tags.NotAuthenticatedTag.class);
            _jspx_th_shiro_005fnotAuthenticated_005f0.setPageContext(_jspx_page_context);
            _jspx_th_shiro_005fnotAuthenticated_005f0.setParent(null);
            int _jspx_eval_shiro_005fnotAuthenticated_005f0 = _jspx_th_shiro_005fnotAuthenticated_005f0.doStartTag();
            if (_jspx_eval_shiro_005fnotAuthenticated_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
                do {
                    out.write("\n");
                    out.write("                        <a type=\"button\" class=\"btn btn-info\" href=\"");
                    out.print(request.getContextPath());
                    out.write("/user/loginPage\">登录</a>\n");
                    out.write("                        <a type=\"button\" class=\"btn btn-info\" href=\"");
                    out.print(request.getContextPath());
                    out.write("/user/registerPage\">注册</a>\n");
                    out.write("                    ");
                    int evalDoAfterBody = _jspx_th_shiro_005fnotAuthenticated_005f0.doAfterBody();
                    if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
                        break;
                } while (true);
            }
            if (_jspx_th_shiro_005fnotAuthenticated_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
                _005fjspx_005ftagPool_005fshiro_005fnotAuthenticated.reuse(_jspx_th_shiro_005fnotAuthenticated_005f0);
                return;
            }
            _005fjspx_005ftagPool_005fshiro_005fnotAuthenticated.reuse(_jspx_th_shiro_005fnotAuthenticated_005f0);
            out.write("\n");
            out.write("                    ");
            //  shiro:authenticated
            org.apache.shiro.web.tags.AuthenticatedTag _jspx_th_shiro_005fauthenticated_005f0 = (org.apache.shiro.web.tags.AuthenticatedTag) _005fjspx_005ftagPool_005fshiro_005fauthenticated.get(org.apache.shiro.web.tags.AuthenticatedTag.class);
            _jspx_th_shiro_005fauthenticated_005f0.setPageContext(_jspx_page_context);
            _jspx_th_shiro_005fauthenticated_005f0.setParent(null);
            int _jspx_eval_shiro_005fauthenticated_005f0 = _jspx_th_shiro_005fauthenticated_005f0.doStartTag();
            if (_jspx_eval_shiro_005fauthenticated_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
                do {
                    out.write("\n");
                    out.write("                        <a type=\"button\" class=\"btn btn-info\"\n");
                    out.write("                           href=\"");
                    out.print(request.getContextPath());
                    out.write("/order/myOrder/");
                    out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.uId}", java.lang.String.class, (javax.servlet.jsp.PageContext) _jspx_page_context, null));
                    out.write("\">我的订单</a>\n");
                    out.write("                        <a type=\"button\" class=\"btn btn-info\"\n");
                    out.write("                           href=\"");
                    out.print(request.getContextPath());
                    out.write("/cart/cart\">我的购物车</a>\n");
                    out.write("                    ");
                    int evalDoAfterBody = _jspx_th_shiro_005fauthenticated_005f0.doAfterBody();
                    if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
                        break;
                } while (true);
            }
            if (_jspx_th_shiro_005fauthenticated_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
                _005fjspx_005ftagPool_005fshiro_005fauthenticated.reuse(_jspx_th_shiro_005fauthenticated_005f0);
                return;
            }
            _005fjspx_005ftagPool_005fshiro_005fauthenticated.reuse(_jspx_th_shiro_005fauthenticated_005f0);
            out.write("\n");
            out.write("                    <!-- User Account: -->\n");
            out.write("                    ");
            //  shiro:authenticated
            org.apache.shiro.web.tags.AuthenticatedTag _jspx_th_shiro_005fauthenticated_005f1 = (org.apache.shiro.web.tags.AuthenticatedTag) _005fjspx_005ftagPool_005fshiro_005fauthenticated.get(org.apache.shiro.web.tags.AuthenticatedTag.class);
            _jspx_th_shiro_005fauthenticated_005f1.setPageContext(_jspx_page_context);
            _jspx_th_shiro_005fauthenticated_005f1.setParent(null);
            int _jspx_eval_shiro_005fauthenticated_005f1 = _jspx_th_shiro_005fauthenticated_005f1.doStartTag();
            if (_jspx_eval_shiro_005fauthenticated_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
                do {
                    out.write("\n");
                    out.write("                        <li class=\"dropdown user user-menu\">\n");
                    out.write("                            <a href=\"#\" class=\"dropdown-toggle\" data-toggle=\"dropdown\">\n");
                    out.write("                                <img src=\"");
                    out.print(request.getContextPath());
                    out.write("/img/2.jpg\" class=\"user-image\" alt=\"User Image\">\n");
                    out.write("                                <span class=\"hidden-xs\">");
                    out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.nickname}", java.lang.String.class, (javax.servlet.jsp.PageContext) _jspx_page_context, null));
                    out.write("</span>\n");
                    out.write("                            </a>\n");
                    out.write("                            <ul class=\"dropdown-menu\">\n");
                    out.write("                                <!-- User image -->\n");
                    out.write("                                <li class=\"user-header\">\n");
                    out.write("                                    <img id=\"user-header\" src=\"");
                    out.print(request.getContextPath());
                    out.write("/img/2.jpg\"\n");
                    out.write("                                         class=\"img-circle\"\n");
                    out.write("                                         alt=\"User Image\">\n");
                    out.write("                                    <p>");
                    out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.nickname}", java.lang.String.class, (javax.servlet.jsp.PageContext) _jspx_page_context, null));
                    out.write("</p>\n");
                    out.write("                                </li>\n");
                    out.write("                                <!--Menu Body-->\n");
                    out.write("                                <li class=\"user-body\">\n");
                    out.write("                                    <div class=\"col-xs-4 text-center\">\n");
                    out.write("                                        <a href=\"#\">Followers</a>\n");
                    out.write("                                    </div>\n");
                    out.write("                                    <div class=\"col-xs-4 text-center\">\n");
                    out.write("                                        <a href=\"#\">Sales</a>\n");
                    out.write("                                    </div>\n");
                    out.write("                                    <div class=\"col-xs-4 text-center\">\n");
                    out.write("                                        <a href=\"#\">Friends</a>\n");
                    out.write("                                    </div>\n");
                    out.write("                                </li>\n");
                    out.write("                                <!-- Menu Footer-->\n");
                    out.write("                                <li class=\"user-footer\">\n");
                    out.write("                                    <div class=\"pull-left\">\n");
                    out.write("                                        <a id=\"systemsettingBtn\" href=\"javascript:void(0)\"\n");
                    out.write("                                           class=\"btn btn-default btn-flat\">修改密码</a>\n");
                    out.write("                                    </div>\n");
                    out.write("                                    <div class=\"pull-right\">\n");
                    out.write("                                        <a href=\"/user/logOut\" class=\"btn btn-default btn-flat\">注销</a>\n");
                    out.write("                                    </div>\n");
                    out.write("                                </li>\n");
                    out.write("                            </ul>\n");
                    out.write("                        </li>\n");
                    out.write("                    ");
                    int evalDoAfterBody = _jspx_th_shiro_005fauthenticated_005f1.doAfterBody();
                    if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
                        break;
                } while (true);
            }
            if (_jspx_th_shiro_005fauthenticated_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
                _005fjspx_005ftagPool_005fshiro_005fauthenticated.reuse(_jspx_th_shiro_005fauthenticated_005f1);
                return;
            }
            _005fjspx_005ftagPool_005fshiro_005fauthenticated.reuse(_jspx_th_shiro_005fauthenticated_005f1);
            out.write("\n");
            out.write("                </ul>\n");
            out.write("            </div>\n");
            out.write("        </nav>\n");
            out.write("    </header>\n");
            out.write("    <aside class=\"main-sidebar\">\n");
            out.write("        <!-- sidebar: style can be found in sidebar.less -->\n");
            out.write("        <section class=\"sidebar\">\n");
            out.write("            <!-- Sidebar user panel -->\n");
            out.write("            <!-- sidebar menu: : style can be found in sidebar.less -->\n");
            out.write("            <ul class=\"sidebar-menu\">\n");
            out.write("                <li>\n");
            out.write("                    <a href=\"");
            out.print(request.getContextPath());
            out.write("/book/toindex\">\n");
            out.write("                        <i class=\"fa fa-dashboard\"></i> <span>首页</span>\n");
            out.write("                    </a>\n");
            out.write("                </li>\n");
            out.write("                ");
            //  shiro:hasAnyRoles
            org.apache.shiro.web.tags.HasAnyRolesTag _jspx_th_shiro_005fhasAnyRoles_005f0 = (org.apache.shiro.web.tags.HasAnyRolesTag) _005fjspx_005ftagPool_005fshiro_005fhasAnyRoles_0026_005fname.get(org.apache.shiro.web.tags.HasAnyRolesTag.class);
            _jspx_th_shiro_005fhasAnyRoles_005f0.setPageContext(_jspx_page_context);
            _jspx_th_shiro_005fhasAnyRoles_005f0.setParent(null);
            // /../WEB-INF/views/commons/nav.jsp(90,16) name = name type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
            _jspx_th_shiro_005fhasAnyRoles_005f0.setName("admin,superadmin");
            int _jspx_eval_shiro_005fhasAnyRoles_005f0 = _jspx_th_shiro_005fhasAnyRoles_005f0.doStartTag();
            if (_jspx_eval_shiro_005fhasAnyRoles_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
                do {
                    out.write("\n");
                    out.write("                    <li>\n");
                    out.write("                        <a href=\"");
                    out.print(request.getContextPath());
                    out.write("/backend/user/getAllUser\">\n");
                    out.write("                            <i class=\"fa fa-th\"></i> <span>普通用户管理</span>\n");
                    out.write("                        </a>\n");
                    out.write("                    </li>\n");
                    out.write("                    <li>\n");
                    out.write("                        <a href=\"");
                    out.print(request.getContextPath());
                    out.write("/backend/book/getAllBook\">\n");
                    out.write("                            <i class=\"fa fa-dashboard\"></i> <span>书籍管理</span>\n");
                    out.write("                        </a>\n");
                    out.write("                    </li>\n");
                    out.write("                ");
                    int evalDoAfterBody = _jspx_th_shiro_005fhasAnyRoles_005f0.doAfterBody();
                    if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
                        break;
                } while (true);
            }
            if (_jspx_th_shiro_005fhasAnyRoles_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
                _005fjspx_005ftagPool_005fshiro_005fhasAnyRoles_0026_005fname.reuse(_jspx_th_shiro_005fhasAnyRoles_005f0);
                return;
            }
            _005fjspx_005ftagPool_005fshiro_005fhasAnyRoles_0026_005fname.reuse(_jspx_th_shiro_005fhasAnyRoles_005f0);
            out.write("\n");
            out.write("                ");
            //  shiro:hasRole
            org.apache.shiro.web.tags.HasRoleTag _jspx_th_shiro_005fhasRole_005f0 = (org.apache.shiro.web.tags.HasRoleTag) _005fjspx_005ftagPool_005fshiro_005fhasRole_0026_005fname.get(org.apache.shiro.web.tags.HasRoleTag.class);
            _jspx_th_shiro_005fhasRole_005f0.setPageContext(_jspx_page_context);
            _jspx_th_shiro_005fhasRole_005f0.setParent(null);
            // /../WEB-INF/views/commons/nav.jsp(102,16) name = name type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
            _jspx_th_shiro_005fhasRole_005f0.setName("superadmin");
            int _jspx_eval_shiro_005fhasRole_005f0 = _jspx_th_shiro_005fhasRole_005f0.doStartTag();
            if (_jspx_eval_shiro_005fhasRole_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
                do {
                    out.write("\n");
                    out.write("                    <li>\n");
                    out.write("                        <a href=\"");
                    out.print(request.getContextPath());
                    out.write("/backend/user/getadmin\">\n");
                    out.write("                            <i class=\"fa fa-th\"></i> <span>管理员管理</span>\n");
                    out.write("                        </a>\n");
                    out.write("                    </li>\n");
                    out.write("                ");
                    int evalDoAfterBody = _jspx_th_shiro_005fhasRole_005f0.doAfterBody();
                    if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
                        break;
                } while (true);
            }
            if (_jspx_th_shiro_005fhasRole_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
                _005fjspx_005ftagPool_005fshiro_005fhasRole_0026_005fname.reuse(_jspx_th_shiro_005fhasRole_005f0);
                return;
            }
            _005fjspx_005ftagPool_005fshiro_005fhasRole_0026_005fname.reuse(_jspx_th_shiro_005fhasRole_005f0);
            out.write("\n");
            out.write("\n");
            out.write("            </ul>\n");
            out.write("        </section>\n");
            out.write("        <!-- /.sidebar -->\n");
            out.write("    </aside>    <!-- Content Wrapper. Contains page content -->\n");
            out.write("    </div>\n");
            out.write("\n");
            out.write("<!-- Content Wrapper. Contains page content -->\n");
            out.write("<div class=\"content-wrapper\">\n");
            out.write("    <!-- Main content -->\n");
            out.write("    <section class=\"content\">\n");
            out.write("        <a type=\"button\" class=\"btn btn-danger\" onclick=\"showChoose()\">目录选择</a>\n");
            out.write("        <div class=\"box-body\" style=\"display: none;\" id=\"chooseType\">\n");
            out.write("            <form action=\"");
            out.print(request.getContextPath());
            out.write("/book/searchByCategory\" method=\"post\">\n");
            out.write("                <select name=\"typeList\" id=\"typeList\">\n");
            out.write("                    <option value=\"\">请选择</option>\n");
            out.write("                </select>\n");
            out.write("                <input type=\"submit\" class=\"btn btn-danger\" value=\"查询\">\n");
            out.write("            </form>\n");
            out.write("        </div>\n");
            out.write("        <form action=\"");
            out.print(request.getContextPath());
            out.write("/book/checkBook\" method=\"post\">\n");
            out.write("            <input type=\"text\" placeholder=\"请填写书籍名\" name=\"bookName\">\n");
            out.write("            <input type=\"submit\" class=\"btn btn-danger\" value=\"查询书籍\">\n");
            out.write("        </form>\n");
            out.write("        <a type=\"button\" class=\"btn btn-danger\"\n");
            out.write("           href=\"");
            out.print(request.getContextPath());
            out.write("/book/Asc\">按价格升序排序</a>\n");
            out.write("        <a type=\"button\" class=\"btn btn-danger\"\n");
            out.write("           href=\"");
            out.print(request.getContextPath());
            out.write("/book/Desc\">按价格降序排序</a>\n");
            out.write("\n");
            out.write("        <div class=\"box box-info\">\n");
            out.write("            <div class=\"box-body\" style=\"display: block;\">\n");
            out.write("                <div class=\"table-responsive\">\n");
            out.write("                    <table class=\"table no-margin\">\n");
            out.write("                        <thead>\n");
            out.write("                        <tr>\n");
            out.write("                            <th>书本作者</th>\n");
            out.write("                            <th>封面</th>\n");
            out.write("                            <th>书名</th>\n");
            out.write("                            <th>价格</th>\n");
            out.write("                            <th>总页数</th>\n");
            out.write("                            <th>出版社</th>\n");
            out.write("                            <th>操作</th>\n");
            out.write("                        </tr>\n");
            out.write("                        </thead>\n");
            out.write("                        <tbody>\n");
            out.write("                        ");
            //  c:forEach
            org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
            _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
            _jspx_th_c_005fforEach_005f0.setParent(null);
            // /index.jsp(44,24) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
            _jspx_th_c_005fforEach_005f0.setVar("book");
            // /index.jsp(44,24) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
            _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/index.jsp(44,24) '${books}'", _el_expressionfactory.createValueExpression(_jspx_page_context.getELContext(), "${books}", java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
            int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[]{0};
            try {
                int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
                if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
                    do {
                        out.write("\n");
                        out.write("                            <tr>\n");
                        out.write("                                <td>");
                        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${book.author}", java.lang.String.class, (javax.servlet.jsp.PageContext) _jspx_page_context, null));
                        out.write("</td>\n");
                        out.write("                                <td><img src=\"");
                        out.print(request.getContextPath());
                        out.write('/');
                        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${book.bookImage}", java.lang.String.class, (javax.servlet.jsp.PageContext) _jspx_page_context, null));
                        out.write("\"\n");
                        out.write("                                         style=\"width: 45px;height: 80px;\"\n");
                        out.write("                                         onclick='showimage(\"");
                        out.print(request.getContextPath());
                        out.write('/');
                        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${book.bookImage}", java.lang.String.class, (javax.servlet.jsp.PageContext) _jspx_page_context, null));
                        out.write("\")'/>\n");
                        out.write("                                </td>\n");
                        out.write("                                <td>");
                        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${book.bookName}", java.lang.String.class, (javax.servlet.jsp.PageContext) _jspx_page_context, null));
                        out.write("</td>\n");
                        out.write("                                <td>");
                        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${book.price}", java.lang.String.class, (javax.servlet.jsp.PageContext) _jspx_page_context, null));
                        out.write("</td>\n");
                        out.write("\n");
                        out.write("                                <td>");
                        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${book.totalPage}", java.lang.String.class, (javax.servlet.jsp.PageContext) _jspx_page_context, null));
                        out.write("</td>\n");
                        out.write("                                <td>");
                        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${book.pubilshing}", java.lang.String.class, (javax.servlet.jsp.PageContext) _jspx_page_context, null));
                        out.write("</td>\n");
                        out.write("                                <td>\n");
                        out.write("                                    <a type=\"button\" class=\"btn btn-danger\" id=\"addCart\"\n");
                        out.write("                                       href=\"");
                        out.print(request.getContextPath());
                        out.write("/cart/add/");
                        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${book.bId}", java.lang.String.class, (javax.servlet.jsp.PageContext) _jspx_page_context, null));
                        out.write("\">加入购物车</a>\n");
                        out.write("                                </td>\n");
                        out.write("                            </tr>\n");
                        out.write("                        ");
                        int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
                        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
                            break;
                    } while (true);
                }
                if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
                    return;
                }
            } catch (java.lang.Throwable _jspx_exception) {
                while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
                    out = _jspx_page_context.popBody();
                _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
            } finally {
                _jspx_th_c_005fforEach_005f0.doFinally();
                _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
            }
            out.write("\n");
            out.write("                        </tbody>\n");
            out.write("                    </table>\n");
            out.write("                </div>\n");
            out.write("            </div>\n");
            out.write("        </div>\n");
            out.write("    </section>\n");
            out.write("</div>\n");
            out.write("<!--分页-->\n");
            out.write("<div class=\"container\">\n");
            out.write("    <nav class=\"text-center\">\n");
            out.write("        <ul class=\"pagination text-center\">\n");
            out.write("            <li><a href=\"");
            out.print(request.getContextPath());
            out.write("/book/");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${url}", java.lang.String.class, (javax.servlet.jsp.PageContext) _jspx_page_context, null));
            out.write("?pageNo=1\"><span>«首页</span> </a></li>\n");
            out.write("            <li>\n");
            out.write("                <a href=\"");
            out.print(request.getContextPath());
            out.write("/book/");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${url}", java.lang.String.class, (javax.servlet.jsp.PageContext) _jspx_page_context, null));
            out.write("?pageNo=");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${(pageInfo.pageNum>1)?(pageInfo.pageNum-1):1}", java.lang.String.class, (javax.servlet.jsp.PageContext) _jspx_page_context, null));
            out.write("\">上一页</a>\n");
            out.write("            </li>\n");
            out.write("            <li>\n");
            out.write("                <a href=\"");
            out.print(request.getContextPath());
            out.write("/book/");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${url}", java.lang.String.class, (javax.servlet.jsp.PageContext) _jspx_page_context, null));
            out.write("?pageNo=");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${(pageInfo.pageNum<pageInfo.pages)?(pageInfo.pageNum+1):pageInfo.pages}", java.lang.String.class, (javax.servlet.jsp.PageContext) _jspx_page_context, null));
            out.write("\">下一页</a>\n");
            out.write("            </li>\n");
            out.write("            <li><a href=\"");
            out.print(request.getContextPath());
            out.write("/book/");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${url}", java.lang.String.class, (javax.servlet.jsp.PageContext) _jspx_page_context, null));
            out.write("?pageNo=");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageInfo.pages}", java.lang.String.class, (javax.servlet.jsp.PageContext) _jspx_page_context, null));
            out.write("\"> <span>末页»</span></a>\n");
            out.write("            </li>\n");
            out.write("            <li class=\"pagespan\">11/12</li>\n");
            out.write("        </ul>\n");
            out.write("    </nav>\n");
            out.write("</div>\n");
            out.write("\n");
            org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../WEB-INF/views/commons/tail.jsp", out, false);
            out.write("\n");
            out.write("\n");
            out.write("<script>\n");
            out.write("\n");
            out.write("    function showChoose() {\n");
            out.write("        $(\"#chooseType\").show();\n");
            out.write("        locationChange();\n");
            out.write("    }\n");
            out.write("\n");
            out.write("    function showimage(source) {\n");
            out.write("        $(\"#imgInModalID\").attr(\"src\", source);\n");
            out.write("        $('.modal').show();\n");
            out.write("    }\n");
            out.write("\n");
            we
            out.write("    function closeModel() {\n");
            out.write("        $('.modal').hide();\n");
            out.write("    }\n");
            out.write("\n");
            out.write("    function locationChange() {\n");
            out.write("        var type = \"\";\n");
            out.write("        var obj = document.getElementById('typeList');\n");
            out.write("        obj.options.length = 0;\n");
            out.write("        $.ajax({\n");
            out.write("            type: \"post\",\n");
            out.write("            url: \"/book/getParentTypeList\",\n");
            out.write("            cache: false,\n");
            out.write("            data: {type: type},\n");
            out.write("            dataType: \"json\",\n");
            out.write("            success: function (result) {\n");
            out.write("                if (result.length > 0) {\n");
            out.write("                    for (var i in result) {\n");
            out.write("                        var selectOption = new Option(result[i].name, result[i].cId);\n");
            out.write("                        obj.add(selectOption);\n");
            out.write("                    }\n");
            out.write("                }\n");
            out.write("            }\n");
            out.write("        });\n");
            out.write("    }\n");
            out.write("\n");
            out.write("\n");
            out.write("</script>\n");
            out.write("</body>\n");
            out.write("</html>\n");
        } catch (java.lang.Throwable t) {
            if (!(t instanceof javax.servlet.jsp.SkipPageException)) {
                out = _jspx_out;
                if (out != null && out.getBufferSize() != 0)
                    try {
                        if (response.isCommitted()) {
                            out.flush();
                        } else {
                            out.clearBuffer();
                        }
                    } catch (java.io.IOException e) {
                    }
                if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
                else throw new ServletException(t);
            }
        } finally {
            _jspxFactory.releasePageContext(_jspx_page_context);
        }
    }
}
